# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d33a6179e541313ddb0af3461cef698ff2821b98a8b2c7facaeaf9d82122ff1115e84b2bd254bdb52d31c0ca62fdff4e030ac91b50a90733c6da2928b2b3f59c

test:
  secret_key_base: 46cbec2815e642085bf312434c1835ca12932fa622193fcacfa1677ccac20c7a5139469aecc324d2f21d5ca1a60ce1c0034b27757346517ffa4650ad92a30431

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
